using PdfDocument;
using PdfDocument.NFe;
using System.Diagnostics;
using System.Globalization;

namespace PdfDocument.Tests;

/// <summary>
/// Validates that the DANFE PDF generated by the library matches
/// the reference PDF (danfe_21250911111111000111558890000000051001234567.pdf)
/// in both data content and layout structure.
/// </summary>
public sealed class DanfeValidationTests
{
    // ── Reference PDF ──────────────────────────────────────────────────
    const string ReferencePdfPath =
        "/home/valdomiro/Downloads/danfe_21250911111111000111558890000000051001234567.pdf";

    // ── XML source ─────────────────────────────────────────────────────
    static readonly string XmlPath = Path.Combine(
        AppDomain.CurrentDomain.BaseDirectory, "nfe-sem-rtc.xml");

    // ═══════════════════════════════════════════════════════════════════
    //  Helpers
    // ═══════════════════════════════════════════════════════════════════

    /// <summary>
    /// Extract plain text from a PDF file using pdftotext with layout preservation.
    /// Returns empty string if pdftotext is not available.
    /// </summary>
    private static string ExtractText(string pdfPath)
    {
        var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "pdftotext",
                Arguments = $"-layout \"{pdfPath}\" -",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            }
        };
        process.Start();
        string output = process.StandardOutput.ReadToEnd();
        process.WaitForExit();
        return output;
    }

    /// <summary>
    /// Extract PDF metadata (page count, page size) using pdfinfo.
    /// </summary>
    private static Dictionary<string, string> ExtractPdfInfo(string pdfPath)
    {
        var info = new Dictionary<string, string>();
        var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "pdfinfo",
                Arguments = $"\"{pdfPath}\"",
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            }
        };
        process.Start();
        string output = process.StandardOutput.ReadToEnd();
        process.WaitForExit();

        foreach (string line in output.Split('\n', StringSplitOptions.RemoveEmptyEntries))
        {
            int colonIdx = line.IndexOf(':');
            if (colonIdx > 0)
            {
                string key = line[..colonIdx].Trim();
                string value = line[(colonIdx + 1)..].Trim();
                info[key] = value;
            }
        }
        return info;
    }

    /// <summary>
    /// Generates a DANFE PDF matching the reference layout using data from NFeData.
    /// This replicates the playground's GenerateEnhancedDanfe method.
    /// </summary>
    private static void GenerateEnhancedDanfe(NFeData data, string outputPath)
    {
        using var pdf = new PdfBuilder();
        var page = pdf.AddPage(595, 842); // A4
        var c = page.Canvas;

        // ── Helpers ────────────────────────────────────────────────────
        void DrawTableRow(ref double yRef, double rowHeight, string[] texts,
            double[] colWidths, double startX = 15, double fontSize = 7,
            PdfCanvas.TextAlign align = PdfCanvas.TextAlign.Left)
        {
            double cellBottom = yRef - rowHeight;
            double x = startX;
            for (int i = 0; i < texts.Length; i++)
            {
                c.DrawCell(texts[i] ?? "", x, cellBottom, colWidths[i],
                    rowHeight, align, fontSize, true);
                x += colWidths[i];
            }
            yRef = cellBottom;
        }

        void DrawSectionTitle(ref double yRef, string title,
            double rowHeight = 10, double fontSize = 7)
        {
            double cellBottom = yRef - rowHeight;
            c.DrawCell(title, 15, cellBottom, 560, rowHeight,
                PdfCanvas.TextAlign.Center, fontSize, true);
            yRef = cellBottom;
        }

        const double RowH = 11;
        const double RowHlabel = 9;

        double y = 815;

        // ── (1) TOP LINE: "RECEBEMOS DE..." + NF-e ────────────────────
        c.DrawText(
            $"RECEBEMOS DE {TruncateTo(data.EmitXNome, 40)} OS PRODUTOS CONSTANTES DA NOTA FISCAL INDICADA ABAIXO",
            15, y, 7);
        c.DrawText("NF-e", 500, y, 12);

        // ── (2) N° + SÉRIE ────────────────────────────────────────────
        y = 783;
        c.DrawText($"N° {FormatNfNumber(data.Nnf)}", 500, y, 9);
        y = 773;
        c.DrawText($"SÉRIE {data.Serie}", 500, y, 8);

        // ── (3) RECEIPT LINE ──────────────────────────────────────────
        y = 793;
        c.DrawLine(15, y, 245, y);
        c.DrawText("DATA DE RECEBIMENTO", 15, y - 8, 6);
        c.DrawLine(255, y, 430, y);
        c.DrawText("IDENTIFICAÇÃO E ASSINATURA DO RECEBEDOR", 255, y - 8, 6);

        // ── (4) EMITENTE (left) | DANFE block (right) ─────────────────
        y = 760;
        c.DrawText(TruncateTo(data.EmitXNome, 50), 15, y, 9);
        y -= 11;
        c.DrawText($"CNPJ: {FormatCnpj(data.EmitCnpj)}", 15, y, 7);
        y -= 10;
        c.DrawText($"{data.EmitXLogr}, {data.EmitNro}", 15, y, 6);
        y -= 9;
        c.DrawText($"{data.EmitXBairro} - {data.EmitXMun}/{data.EmitUf}", 15, y, 6);
        y -= 9;
        c.DrawText($"CEP: {data.EmitCep}", 15, y, 6);

        // Right side: DANFE + chave + barcode
        y = 760;
        c.DrawText("DANFE", 460, y, 16);
        c.DrawText("DOCUMENTO AUXILIAR", 410, y - 14, 7);
        c.DrawText("DA NOTA FISCAL", 415, y - 24, 7);
        c.DrawText("ELETRÔNICA", 420, y - 34, 7);
        c.DrawText("0 - ENTRADA", 410, y - 44, 6);
        c.DrawText("1 - SAÍDA", 410, y - 52, 6);

        // CHAVE DE ACESSO block
        string chaveLimpa = "21250911111111000111558890000000051001234567";
        string chaveFormatada = FormatChaveAcesso(chaveLimpa);
        c.DrawText("CHAVE DE ACESSO", 360, y - 62, 7);
        c.DrawText(chaveFormatada, 360, y - 74, 6);

        // N°/SÉRIE/FOLHA
        c.DrawText($"N°{FormatNfNumber(data.Nnf)}", 470, y - 64, 11);
        c.DrawText($"SÉRIE {data.Serie}", 470, y - 77, 7);
        c.DrawText("FOLHA 1/1", 470, y - 87, 7);

        // Barcode (Code128)
        try
        {
            var barcodeBars = Code128.Generate(chaveLimpa);
            c.DrawBarcode(barcodeBars, 360, y - 50, 0.6, 24);
        }
        catch { }

        // Consulta
        c.DrawText("Consulta de autenticidade no portal nacional da NF-e",
            360, y - 110, 5);
        c.DrawText("www.nfe.fazenda.gov.br/portal ou no site da Sefaz",
            360, y - 118, 5);
        c.DrawText("Autorizadora", 360, y - 126, 5);

        // ── (5) Separator ─────────────────────────────────────────────
        y = y - 130;
        c.DrawLine(15, y, 575, y);
        y -= 3;

        // ── NATUREZA DA OPERAÇÃO | PROTOCOLO ──────────────────────────
        DrawSectionTitle(ref y, "NATUREZA DA OPERAÇÃO");
        double yNat = y + RowH;
        DrawTableRow(ref y, RowH, [TruncateTo(data.NatOp, 40)], [360]);
        double yProt = yNat;
        string protText = string.IsNullOrEmpty(data.NProt)
            ? "" : $"{data.NProt} {FormatDate(data.DhAutor)} {FormatTime(data.DhAutor)}";
        c.DrawCell(TruncateTo(protText, 30), 380, yProt - RowH, 195, RowH,
            PdfCanvas.TextAlign.Left, 7, true);
        y = yProt - RowH;

        // ── INSCRIÇÃO ESTADUAL ────────────────────────────────────────
        DrawSectionTitle(ref y, "INSCRIÇÃO ESTADUAL");
        string ieSt = string.IsNullOrEmpty(data.EmitIeSt) ? "" : data.EmitIeSt;
        DrawTableRow(ref y, RowHlabel,
            ["INSCRIÇÃO ESTADUAL", "INSC.ESTADUAL DO SUBST. TRIBUTÁRIO", "CNPJ"],
            [230, 180, 150], fontSize: 5);
        DrawTableRow(ref y, RowH,
            [FormatIe(data.EmitIe), ieSt, FormatCnpj(data.EmitCnpj)],
            [230, 180, 150]);

        // ── DESTINATÁRIO / REMETENTE ──────────────────────────────────
        DrawSectionTitle(ref y, "DESTINATÁRIO / REMETENTE");
        DrawTableRow(ref y, RowHlabel,
            ["NOME/RAZÃO SOCIAL", "CNPJ/CPF", "DATA DA EMISSÃO"],
            [360, 100, 100], fontSize: 5);
        DrawTableRow(ref y, RowH,
            [TruncateTo(data.DestXNome, 45),
             FormatCpfCnpj(data.DestCnpj),
             FormatDate(data.DhEmi)],
            [360, 100, 100]);

        DrawTableRow(ref y, RowHlabel,
            ["ENDEREÇO", "BAIRRO / DISTRITO", "CEP", "DATA DA SAÍDA/ENTRADA"],
            [260, 150, 70, 80], fontSize: 5);
        DrawTableRow(ref y, RowH,
            [$"{data.DestXLogr}, {data.DestNro}",
             data.DestXBairro,
             FormatCep(data.EmitCep),
             FormatDate(string.IsNullOrEmpty(data.DhSaiEnt)
                 ? data.DhEmi : data.DhSaiEnt)],
            [260, 150, 70, 80]);

        DrawTableRow(ref y, RowHlabel,
            ["MUNICÍPIO", "FONE/FAX", "UF", "INSCRIÇÃO ESTADUAL",
             "HORA DE SAÍDA/ENTRADA"],
            [150, 100, 50, 130, 130], fontSize: 5);
        DrawTableRow(ref y, RowH,
            [data.DestXMun,
             FormatFone(data.DestFone),
             data.DestUf,
             FormatIe(data.DestIe),
             FormatTime(string.IsNullOrEmpty(data.DhSaiEnt)
                 ? data.DhEmi : data.DhSaiEnt)],
            [150, 100, 50, 130, 130]);

        // ── FATURA / DUPLICATAS ───────────────────────────────────────
        y -= 4;
        DrawSectionTitle(ref y, "FATURA / DUPLICATAS");
        DrawTableRow(ref y, RowHlabel, ["FATURA"], [560], fontSize: 6);
        DrawTableRow(ref y, RowHlabel,
            ["Núm. Duplicata/Parcela", "Vencimento", "Valor",
             "Núm. Duplicata/Parcela", "Vencimento", "Valor",
             "Núm. Duplicata/Parcela", "Vencimento", "Valor"],
            [62, 63, 62, 62, 63, 62, 62, 63, 62], fontSize: 5);
        DrawTableRow(ref y, RowH,
            ["", "", "", "", "", "", "", "", ""],
            [62, 63, 62, 62, 63, 62, 62, 63, 62], fontSize: 6);

        // ── CÁLCULO DO IMPOSTO ────────────────────────────────────────
        y -= 4;
        DrawSectionTitle(ref y, "CÁLCULO DO IMPOSTO");
        DrawTableRow(ref y, RowHlabel,
            ["BASE DE CÁLCULO DO ICMS", "VALOR DO ICMS",
             "BASE DE CÁLCULO DO ICMS ST", "VALOR DO ICMS ST",
             "VALOR APROXIMADO DOS TRIBUTOS", "VALOR TOTAL DOS PRODUTOS"],
            [110, 70, 110, 70, 100, 100], fontSize: 5);
        DrawTableRow(ref y, RowH,
            [data.VBc, data.VIcms, data.VBcSt, data.VSt,
             data.VAproxTrib, data.VProdTotal],
            [110, 70, 110, 70, 100, 100]);

        DrawTableRow(ref y, RowHlabel,
            ["VALOR DO FRETE", "VALOR DO SEGURO", "DESCONTO",
             "OUTRAS DESPESAS ACESSÓRIAS", "VALOR DO IPI",
             "VALOR TOTAL DA NOTA"],
            [95, 75, 75, 125, 70, 120], fontSize: 5);
        DrawTableRow(ref y, RowH,
            [data.VFrete, data.VSeg, data.VDesc, data.VOutro, data.VIpi, data.VNf],
            [95, 75, 75, 125, 70, 120]);

        // ── TRANSPORTADOR ─────────────────────────────────────────────
        y -= 4;
        DrawSectionTitle(ref y, "TRANSPORTADOR / VOLUMES TRANSPORTADOS");
        string transNome = string.IsNullOrEmpty(data.TransXNome)
            ? "NÃO INFORMADO" : data.TransXNome;
        DrawTableRow(ref y, RowHlabel,
            ["RAZÃO SOCIAL", "FRETE POR CONTA", "CÓDIGO ANTT",
             "PLACA DO VEÍCULO", "UF", "CNPJ / CPF"],
            [210, 90, 60, 90, 30, 80], fontSize: 5);
        DrawTableRow(ref y, RowH,
            [TruncateTo(transNome, 35),
             FormatFrete(data.ModFrete),
             data.TransAntt,
             data.TransPlaca,
             data.TransUFVeic,
             FormatCpfCnpj(data.TransCnpj)],
            [210, 90, 60, 90, 30, 80]);

        DrawTableRow(ref y, RowHlabel,
            ["ENDEREÇO", "MUNICÍPIO", "UF", "INSCRIÇÃO ESTADUAL"],
            [260, 150, 50, 100], fontSize: 5);
        DrawTableRow(ref y, RowH,
            [data.TransXEnder, data.TransXMun, data.TransUf, data.TransIe],
            [260, 150, 50, 100]);

        DrawTableRow(ref y, RowHlabel,
            ["QUANTIDADE", "ESPÉCIE", "MARCA", "NUMERAÇÃO",
             "PESO BRUTO", "PESO LÍQUIDO"],
            [70, 70, 130, 130, 80, 80], fontSize: 5);
        string qVol = string.IsNullOrEmpty(data.TransQVol) ? "1" : data.TransQVol;
        string esp = string.IsNullOrEmpty(data.TransEspecie)
            ? "VOLUMES" : data.TransEspecie;
        DrawTableRow(ref y, RowH,
            [qVol, esp, data.TransMarca, data.TransNumVol,
             data.TransPesoB, data.TransPesoL],
            [70, 70, 130, 130, 80, 80]);

        // ── DADOS DO PRODUTO ──────────────────────────────────────────
        y -= 4;
        DrawSectionTitle(ref y, "DADOS DO PRODUTO / SERVIÇO");
        DrawTableRow(ref y, RowHlabel,
            ["COD.PROD.", "DESCRIÇÃO DO PRODUTO / SERVIÇO", "NCM/SH",
             "CST", "CFOP", "UNID", "QTDE", "VL. UNITÁRIO", "VL. TOTAL",
             "VL. DESCONTO", "BC.ICMS", "VL.ICMS", "V.IPI",
             "ALÍQ.ICMS", "ALÍQ.IPI"],
            [45, 145, 42, 25, 28, 25, 28, 42, 42, 35, 35, 35, 30, 25, 25],
            fontSize: 4.5f);
        DrawTableRow(ref y, RowH,
            [data.CProd, TruncateTo(data.XProd, 30), data.Ncm,
             data.Cst, data.Cfop, data.UCom, data.QCom, data.VUnCom,
             data.VProd, data.VProdDesc, data.VBcProd, data.VIcmsProd,
             data.VIpiProd, data.PIcms, data.PIpi],
            [45, 145, 42, 25, 28, 25, 28, 42, 42, 35, 35, 35, 30, 25, 25],
            fontSize: 5);

        // ── CÁLCULO DO ISSQN ──────────────────────────────────────────
        y -= 4;
        DrawSectionTitle(ref y, "CÁLCULO DO ISSQN");
        DrawTableRow(ref y, RowHlabel,
            ["INSCRIÇÃO MUNICIPAL", "VALOR TOTAL DOS SERVIÇOS",
             "BASE DE CÁLCULO DO ISSQN", "VALOR DO ISSQN"],
            [140, 140, 140, 140], fontSize: 5);
        DrawTableRow(ref y, RowH,
            ["", "0,00", "0,00", "0,00"],
            [140, 140, 140, 140]);

        // ── DADOS ADICIONAIS ──────────────────────────────────────────
        y -= 4;
        DrawSectionTitle(ref y, "DADOS ADICIONAIS");
        DrawTableRow(ref y, RowHlabel,
            ["INFORMAÇÕES COMPLEMENTARES", "RESERVADO AO FISCO"],
            [355, 205], fontSize: 5);
        string infCpl = string.IsNullOrEmpty(data.InfCpl)
            ? $"Natureza: {data.NatOp}" : data.InfCpl;
        DrawTableRow(ref y, RowH * 3,
            [infCpl, data.InfAdic],
            [355, 205], fontSize: 6, align: PdfCanvas.TextAlign.Left);

        // ── Rodapé ────────────────────────────────────────────────────
        y -= 4;
        DrawTableRow(ref y, RowH,
            [$"N° {FormatNfNumber(data.Nnf)}",
             $"SÉRIE {data.Serie}", "FOLHA 1/1",
             "Documento gerado em ambiente de homologação - Sem valor fiscal"],
            [70, 70, 80, 340], fontSize: 6);

        pdf.Save(outputPath);
    }

    // ── Formatting helpers ────────────────────────────────────────────
    static string TruncateTo(string text, int maxLen)
    {
        if (string.IsNullOrEmpty(text)) return "";
        return text.Length <= maxLen ? text : text[..(maxLen - 3)] + "...";
    }

    static string FormatCnpj(string cnpj)
    {
        if (string.IsNullOrEmpty(cnpj) || cnpj.Length < 14) return cnpj;
        return $"{cnpj[..2]}.{cnpj[2..5]}.{cnpj[5..8]}/{cnpj[8..12]}-{cnpj[12..14]}";
    }

    static string FormatCpfCnpj(string doc)
    {
        if (string.IsNullOrEmpty(doc)) return "";
        string clean = doc.Replace(".", "").Replace("-", "").Replace("/", "");
        return clean.Length <= 11
            ? $"{clean[..3]}.{clean[3..6]}.{clean[6..9]}-{clean[9..11]}"
            : FormatCnpj(clean);
    }

    static string FormatDate(string isoDate)
    {
        if (string.IsNullOrEmpty(isoDate) || isoDate.Length < 10) return isoDate;
        return $"{isoDate[8..10]}/{isoDate[5..7]}/{isoDate[..4]}";
    }

    static string FormatTime(string isoDate)
    {
        if (string.IsNullOrEmpty(isoDate) || isoDate.Length < 19) return "";
        return isoDate[11..19];
    }

    static string FormatNfNumber(string nnf)
    {
        if (string.IsNullOrEmpty(nnf)) return "";
        return nnf.PadLeft(9, '0').Insert(3, ".").Insert(7, ".");
    }

    static string FormatChaveAcesso(string chave)
    {
        // Groups of 4 digits
        if (string.IsNullOrEmpty(chave) || chave.Length < 44) return chave;
        var parts = new List<string>();
        for (int i = 0; i < chave.Length; i += 4)
            parts.Add(chave[i..Math.Min(i + 4, chave.Length)]);
        return string.Join(" ", parts);
    }

    static string FormatCep(string cep)
    {
        if (string.IsNullOrEmpty(cep) || cep.Length < 8) return cep;
        return $"{cep[..5]}-{cep[5..8]}";
    }

    static string FormatIe(string ie)
    {
        if (string.IsNullOrEmpty(ie)) return "";
        if (ie.Length >= 9 && ie.All(char.IsDigit))
            return $"{ie[..3]}.{ie[3..6]}.{ie[6..]}";
        return ie;
    }

    static string FormatFone(string fone)
    {
        if (string.IsNullOrEmpty(fone)) return "";
        string clean = fone.Replace(" ", "").Replace("-", "").Replace(".", "");
        if (clean.Length == 10)
            return $"({clean[..2]}) {clean[2..6]}-{clean[6..]}";
        if (clean.Length == 11)
            return $"({clean[..2]}) {clean[2..7]}-{clean[7..]}";
        return fone;
    }

    static string FormatFrete(string modFrete)
    {
        return modFrete switch
        {
            "0" => "0 - Por conta do Emitente",
            "1" => "1 - Por conta do Destinatário",
            "2" => "2 - Por conta de Terceiros",
            _ => modFrete
        };
    }

    // ═══════════════════════════════════════════════════════════════════
    //  Tests
    // ═══════════════════════════════════════════════════════════════════

    [Fact]
    public void Validate_PdfInfo_Matches_Reference()
    {
        if (!File.Exists(ReferencePdfPath) || !File.Exists(XmlPath))
            return;

        // Arrange: generate DANFE
        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);
            Assert.True(File.Exists(generatedPath), "Generated PDF should exist");
            Assert.True(new FileInfo(generatedPath).Length > 0,
                "Generated PDF should not be empty");

            // Extract PDF metadata
            var refInfo = ExtractPdfInfo(ReferencePdfPath);
            var genInfo = ExtractPdfInfo(generatedPath);

            // Assert page count
            Assert.True(refInfo.ContainsKey("Pages"), "Reference PDF should have Pages info");
            string refPages = refInfo.GetValueOrDefault("Pages", "");
            string genPages = genInfo.GetValueOrDefault("Pages", "");
            Assert.Equal(refPages, genPages);

            // Assert page size (both A4)
            if (refInfo.TryGetValue("Page size", out var refPageSize))
            {
                Assert.True(genInfo.TryGetValue("Page size", out var genPageSize),
                    "Generated PDF should have Page size info");
                // Both should be approximately A4: 595 x 842 pts
                Assert.Contains("595", genPageSize);
                Assert.Contains("842", genPageSize);
            }
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }

    [Fact]
    public void Validate_Emitente_Data_Matches_Reference()
    {

        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);

            string refText = ExtractText(ReferencePdfPath);
            string genText = ExtractText(generatedPath);

            // ── Emitente name ─────────────────────────────────────────
            Assert.Contains("EMPRESA EXEMPLO LTDA", genText); // Generated PDF should contain emitente name

            // ── Emitente CNPJ (formatted) ─────────────────────────────
            string cnpjFormatted = FormatCnpj(data.EmitCnpj);
            Assert.Contains(cnpjFormatted, genText); // Generated PDF should contain CNPJ: {cnpjFormatted}

            // ── Emitente address ──────────────────────────────────────
            Assert.Contains(data.EmitXLogr, genText); // Generated PDF should contain address: {data.EmitXLogr}
            Assert.Contains(data.EmitXMun, genText); // Generated PDF should contain municipality: {data.EmitXMun}
            Assert.Contains(data.EmitUf, genText); // Generated PDF should contain UF: {data.EmitUf}

            // ── Emitente IE ───────────────────────────────────────────
            if (!string.IsNullOrEmpty(data.EmitIe))
            {
                Assert.Contains(FormatIe(data.EmitIe), genText); // Generated PDF should contain IE: {FormatIe(data.EmitIe)}
            }
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }

    [Fact]
    public void Validate_Destinatario_Data_Matches_Reference()
    {

        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);

            string genText = ExtractText(generatedPath);

            // ── Destinatário name ─────────────────────────────────────
            string destNome = "NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO";
            Assert.Contains(destNome, genText); // Generated PDF should contain destinatário name

            // ── Destinatário CNPJ ─────────────────────────────────────
            string destCnpj = FormatCpfCnpj(data.DestCnpj);
            Assert.Contains(destCnpj, genText); // Generated PDF should contain dest CNPJ: {destCnpj}

            // ── Destinatário address ──────────────────────────────────
            Assert.Contains(data.DestXLogr, genText); // Generated PDF should contain dest address: {data.DestXLogr}
            Assert.Contains(data.DestXBairro, genText); // Generated PDF should contain dest neighborhood: {data.DestXBairro}
            Assert.Contains(data.DestXMun, genText); // Generated PDF should contain dest municipality: {data.DestXMun}
            Assert.Contains(data.DestUf, genText); // Generated PDF should contain dest UF: {data.DestUf}

            // ── Data emissão formatted ────────────────────────────────
            string formattedDate = FormatDate(data.DhEmi);
            Assert.Contains(formattedDate, genText); // Generated PDF should contain emission date: {formattedDate}
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }

    [Fact]
    public void Validate_NFe_Identification_Matches_Reference()
    {

        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);

            string genText = ExtractText(generatedPath);

            // ── DANFE title ───────────────────────────────────────────
            Assert.Contains("DANFE", genText); // Generated PDF should contain DANFE title
            Assert.Contains("DOCUMENTO AUXILIAR", genText); // Generated PDF should contain DOCUMENTO AUXILIAR
            Assert.Contains("DA NOTA FISCAL", genText); // Generated PDF should contain DA NOTA FISCAL
            Assert.Contains("ELETRÔNICA", genText); // Generated PDF should contain ELETRÔNICA

            // ── Chave de acesso ───────────────────────────────────────
            Assert.Contains("CHAVE DE ACESSO", genText); // Generated PDF should contain CHAVE DE ACESSO section
            // Check first group of 4 digits
            Assert.Contains("2125", genText); // Generated PDF should contain first group of chave
            // Check last 4 digits
            Assert.Contains("4567", genText); // Generated PDF should contain last group of chave

            // ── NFe number and series ─────────────────────────────────
            Assert.Contains(data.Serie, genText); // Generated PDF should contain série: {data.Serie}

            // ── FOLHA ────────────────────────────────────────────────
            Assert.Contains("FOLHA 1/1", genText); // Generated PDF should contain FOLHA 1/1

            // ── Natureza da operação ──────────────────────────────────
            Assert.Contains("NATUREZA DA OPERAÇÃO", genText); // Generated PDF should contain NATUREZA DA OPERAÇÃO
            Assert.Contains("Compra", genText); // Generated PDF should contain natureza text

            // ── Protocolo data ─────────────────────────────────────────
            // (appears inline next to NATUREZA in reference layout)
            if (!string.IsNullOrEmpty(data.NProt))
            {
                Assert.Contains(data.NProt, genText);
            }
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }

    [Fact]
    public void Validate_Totals_And_Tax_Data_Matches_Reference()
    {

        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);

            string genText = ExtractText(generatedPath);

            // ── Cálculo do Imposto section ────────────────────────────
            Assert.Contains("CÁLCULO DO IMPOSTO", genText); // Generated PDF should contain CÁLCULO DO IMPOSTO

            // ── Key tax fields ────────────────────────────────────────
            Assert.Contains("BASE DE CÁLCULO DO ICMS", genText); // Generated PDF should contain BC ICMS
            Assert.Contains("VALOR DO ICMS", genText); // Generated PDF should contain VL ICMS
            Assert.Contains("VALOR TOTAL DOS PRODUTOS", genText); // Generated PDF should contain VL Total Produtos
            Assert.Contains("VALOR TOTAL DA NOTA", genText); // Generated PDF should contain VL Total NF

            // ── Frete, Seguro, Desconto fields ────────────────────────
            Assert.Contains("VALOR DO FRETE", genText); // Generated PDF should contain VL Frete
            Assert.Contains("VALOR DO SEGURO", genText); // Generated PDF should contain VL Seguro
            Assert.Contains("DESCONTO", genText); // Generated PDF should contain Desconto

            // ── Valor total NF ────────────────────────────────────────
            Assert.Contains(data.VNf, genText); // Generated PDF should contain NF value: {data.VNf}
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }

    [Fact]
    public void Validate_Transportador_Data_Matches_Reference()
    {

        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);

            string genText = ExtractText(generatedPath);

            // ── Transportador section ─────────────────────────────────
            Assert.Contains("TRANSPORTADOR", genText); // Generated PDF should contain TRANSPORTADOR

            // ── Transportador name ────────────────────────────────────
            Assert.Contains(TruncateTo(data.TransXNome, 30), genText); // Generated PDF should contain carrier name

            // ── Transportador CNPJ ────────────────────────────────────
            if (!string.IsNullOrEmpty(data.TransCnpj))
            {
                string cnpjTrans = FormatCpfCnpj(data.TransCnpj);
                Assert.Contains(cnpjTrans, genText); // Generated PDF should contain carrier CNPJ: {cnpjTrans}
            }

            // ── Volume data ───────────────────────────────────────────
            if (!string.IsNullOrEmpty(data.TransQVol))
            {
                Assert.Contains(data.TransQVol, genText); // Generated PDF should contain qVol: {data.TransQVol}
            }
            if (!string.IsNullOrEmpty(data.TransEspecie))
            {
                Assert.Contains(data.TransEspecie, genText); // Generated PDF should contain espécie: {data.TransEspecie}
            }
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }

    [Fact]
    public void Validate_Product_Data_Matches_Reference()
    {

        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);

            string genText = ExtractText(generatedPath);

            // ── Product section ───────────────────────────────────────
            Assert.Contains("DADOS DO PRODUTO", genText); // Generated PDF should contain DADOS DO PRODUTO

            // ── Product code ──────────────────────────────────────────
            Assert.Contains(data.CProd, genText); // Generated PDF should contain product code: {data.CProd}

            // ── Product description ───────────────────────────────────
            Assert.Contains(TruncateTo(data.XProd, 25), genText); // Generated PDF should contain product description

            // ── NCM ───────────────────────────────────────────────────
            Assert.Contains(data.Ncm, genText); // Generated PDF should contain NCM: {data.Ncm}

            // ── CFOP ──────────────────────────────────────────────────
            Assert.Contains(data.Cfop, genText); // Generated PDF should contain CFOP: {data.Cfop}

            // ── Unit ──────────────────────────────────────────────────
            Assert.Contains(data.UCom, genText); // Generated PDF should contain unit: {data.UCom}

            // ── Quantity ──────────────────────────────────────────────
            Assert.Contains(data.QCom, genText); // Generated PDF should contain quantity: {data.QCom}
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }

    [Fact]
    public void Validate_Layout_Sections_Present_In_Correct_Order()
    {

        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);

            string refText = ExtractText(ReferencePdfPath);
            string genText = ExtractText(generatedPath);

            // ── Ordered section titles that must appear ───────────────
            string[] requiredSections =
            [
                "DANFE",
                "CHAVE DE ACESSO",
                "NATUREZA DA OPERAÇÃO",
                "INSCRIÇÃO ESTADUAL",
                "DESTINATÁRIO / REMETENTE",
                "FATURA / DUPLICATAS",
                "CÁLCULO DO IMPOSTO",
                "TRANSPORTADOR / VOLUMES TRANSPORTADOS",
                "DADOS DO PRODUTO / SERVIÇO",
                "CÁLCULO DO ISSQN",
                "DADOS ADICIONAIS",
            ];

            // ── Verify each section appears in the text ───────────────
            foreach (string section in requiredSections)
            {
                Assert.Contains(section, genText); // Generated PDF must contain section: '{section}'
            }

            // ── Verify sections appear in correct order ───────────────
            // (index of each section in text must be increasing)
            int lastIndex = -1;
            foreach (string section in requiredSections)
            {
                int idx = genText.IndexOf(section, StringComparison.Ordinal);
                Assert.True(idx >= 0,
                    $"Section '{section}' should be present in generated PDF");
                Assert.True(idx > lastIndex,
                    $"Section '{section}' should appear after previous section. " +
                    $"Found at index {idx}, previous was at {lastIndex}.");
                lastIndex = idx;
            }

            // ── Footer disclaimer must be present ─────────────────────
            Assert.Contains("ambiente de homologação", genText); // Generated PDF should contain homologação disclaimer
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }

    [Fact]
    public void Validate_Barcode_Present()
    {
        if (!File.Exists(XmlPath))
            return;

        var data = new NFeParser().Parse(XmlPath);
        string generatedPath = Path.GetTempFileName() + ".pdf";

        try
        {
            GenerateEnhancedDanfe(data, generatedPath);

            // Read the PDF as text to check barcode stream exists
            string pdfContent = File.ReadAllText(generatedPath);

            // Code128 barcode should generate content streams
            // The barcode is rendered as filled rectangles (re operator in PDF)
            // Check for the barcode-related content
            Assert.Contains("CHAVE DE ACESSO", pdfContent); // PDF should contain CHAVE DE ACESSO text

            // Verify code128 barcode patterns are in the PDF stream
            // The barcode generates 're' (rectangle) operations
            Assert.Contains("re", pdfContent); // PDF should contain rectangle drawing operations (barcode)
        }
        finally
        {
            if (File.Exists(generatedPath)) File.Delete(generatedPath);
        }
    }
}
